### ISSUE TITLE
求教：UML类图是用哪个软件画的啊~？

### ISSUE THREAD

**Issue by Edwards666** [seaswalker/Spring#39]
请问UML类图是用哪个软件画的啊~

**Comment by Edwards666** [comment]
像这种的
![image](https://github.com/seaswalker/spring-analysis/assets/37021347/1edfc185-d89a-4306-b509-2026c9b7df79)

**Comment by 414507259** [comment]
processon



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月16日(周日) 中午11:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [seaswalker/spring-analysis] 求教：UML类图是用哪个软件画的啊~？ (Issue #39)




 
像这种的

**Comment by seaswalker** [comment]
StarUML
